name: automated refactorings

on:
  pull_request: ~
  push: ~
  schedule:
      # Do not make it the first of the month and/or midnight since it is a very busy time
      - cron: '* 10 5 * *'
  workflow_dispatch: ~

jobs:
  automated-refactorings:
    name: automated-refactorings
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: ['8.4']
        symfony: ['7.3.*']

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: set up php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer, flex

      - name: install composer dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
          COMPOSER_PREFER_STABLE: 1
        uses: ramsey/composer-install@v3

      - name: check automated refactorings
        run: vendor/bin/rector --dry-run --ansi
